# Generated by Django 5.0.1 on 2024-02-25 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('_id', models.UUIDField(default='3ad0e0a085284bada221f5ac030c0556', editable=False, primary_key=True, serialize=False)),
                ('channelName', models.CharField(db_column='channel_name', max_length=100, null=True)),
                ('channelHandle', models.CharField(db_column='channel_handle', max_length=100, null=True)),
                ('channelDescription', models.TextField(db_column='channel_description')),
                ('channelAvatarUrl', models.CharField(db_column='channel_avatar_url', max_length=5000)),
                ('channelAvatarId', models.CharField(db_column='channel_avatar_id', max_length=200)),
                ('channelBackgroundUrl', models.CharField(db_column='channel_background_url', max_length=5000)),
                ('channelBackgroundId', models.CharField(db_column='channel_background_id', max_length=200)),
            ],
            options={
                'db_table': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.UUIDField(default='41266e5cb4ab4acbabf57fe2bdd17f40', editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('avatar', models.CharField(max_length=5000)),
                ('avatar_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500, unique=True)),
                ('refreshToken', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='main.channel')),
                ('subscriber', models.ForeignKey(db_column='subscriber_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='main.user')),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('_id', models.UUIDField(default='d2ce8238d7ee43bf8b98102fdfa69554', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=100)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('thumbnail_id', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, to='main.channel')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
